# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d4ccb1df-9ea1-4876-a39c-cd8892af717d";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:2" "noatime" ];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/5d7efbd7-4702-4777-88d1-aa168e645e77";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/d4ccb1df-9ea1-4876-a39c-cd8892af717d";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:2" "relatime" ];
    };

  fileSystems."/swapfile" =
    { device = "/dev/disk/by-uuid/d4ccb1df-9ea1-4876-a39c-cd8892af717d";
      fsType = "btrfs";
      options = [ "subvol=@swapfile" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BF6E-2EE4";
      fsType = "vfat";
    };

  swapDevices = [ { device = "/swapfile/swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp166s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
